name: Automated Tests

on:
  pull_request

env:
  MODE: production

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry export --without-hashes --format=requirements.txt > requirements.txt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Create env file
      working-directory: .
      run: |
        echo "${{ secrets.ENV_FILE }}" > configurations/.env.production
    - name: Test with pytest
      run: |
        coverage run -m pytest
        coverage report
        coverage xml
    - name: Get Coverage report
      uses: orgoro/coverage@v3
      with:
        coverageFile: coverage.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        thresholdAll: 0.0
        thresholdNew: 0.6
        thresholdModified: 0.0
