name: Automated Tests

on:
  pull_request

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry export --without-hashes --format=requirements.txt > requirements.txt
    - name: Run tests with coverage
      run: pytest --cov=server/ tests/
    - name: Generate coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: htmlcov/
